### ISSUE TITLE
Make tmp path configurable

### ISSUE THREAD

**Issue by dharmeshkakadia** [andyzhangx/kubernetes-drivers#10]
While running k8s flexdriver with blobfuse, accessing a large file on blob results into kubelet eviction due to disk space issue. It looks like its filling up the disk space. I see that /tmp/blobfuse/ is hard coded as a path for cache and thats probably not the location most machine on azure has any space.

**Comment by dharmeshkakadia** [comment]
cc @seguler

**Comment by dharmeshkakadia** [comment]
Any updates?

**Comment by andyzhangx** [comment]
It's already supported:
https://github.com/Azure/kubernetes-volume-drivers/tree/master/flexvolume/blobfuse

Pls note that this repo https://github.com/andyzhangx/kubernetes-drivers is deprecated, all dev work has been moved to https://github.com/Azure/kubernetes-volume-drivers

There are a few changes for this driver:
## 1. `kubelet` **must** run as native daemon
 Old k8s cluster on which kubelet is running inside a container is not supported for this blobfuse driver now:
`kubelet` **must** run as native daemon (other than containerized kubelet), `kubelet` in [acs-engine v0.16.0 or above](https://github.com/Azure/acs-engine) and [AKS](https://azure.microsoft.com/en-us/services/container-service/) cluster are already running as native daemon.

## 2. install blobfuse driver on every agent node
Please refer to [Install from Apt/Yum Package Repositories](https://github.com/Azure/azure-storage-fuse/wiki/1.-Installation#option-1---install-from-aptyum-package-repositories)

## 3. install `jq` package on every agent node
```
sudo apt install jq -y
```

## 4. Added a new parameter(`tmppath`) in example, you could specify what `tmp-path` as you want
https://github.com/Azure/kubernetes-volume-drivers/blob/master/flexvolume/blobfuse/nginx-flex-blobfuse.yaml#L21
